config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: "home#index"
  #devise_for :users
  
  devise_for :users, controllers: { sessions: 'users/sessions', 
    registrations: 'users/registrations',
  }

  namespace :users do
    resources :admins
    resources :employees 
    
  end

  resources :leaves
  resources :attendances
  resources :salaries
  resources :tax_deductions
  resources :payslips
 
  #get '/my_leaves/:current_user.id', to: 'leaves#my_leaves'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
   def index
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_dropdown.html.erb
<table class="table table-striped", style=" border-spacing: 100px;">

  <thead>
    <tr>
      <th scope="col"></th>
    </tr>
  </thead>

  <tbody>

    <% if current_user == Admin.last%>

      <tr>
        <th scope="row", class="table-secondary" style="padding: 15px"><%= link_to "New Employee", new_users_employee_path, class: "btn " %></th>
      </tr>   

      <tr>
        <th scope="row", class="table-success" style="padding: 15px" ><%= link_to "All employees",  users_employees_path, class: "btn"%></th>
      </tr>
     <% end %>

    <tr>
      <th scope="row", class="table-danger" style="padding: 15px"><%= link_to "Leaves", leaves_path, class: "btn" %></th>     
    </tr>

    <tr>
     <th scope="row", class="table-warning" style="padding: 15px"><%= link_to "Attendance", attendances_path, class: "btn "%> </th>   
    </tr>

    <tr>
      <th scope="row", class="table-info" style="padding: 15px"><%= link_to "Salary", salaries_path, class: "btn "%></th>     
    </tr>

    <tr>
      <th scope="row", class="table-danger" style="padding: 15px"><%= link_to "Tax Deductions", tax_deductions_path, class: "btn "%></th>     
    </tr>

    <tr>
      <th scope="row", class="table-success" style="padding: 15px"><%= link_to "Payslip", payslips_path, class: "btn" %></th>     
    </tr>

  </tbody>
  
</table>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">

  <div class="container-fluid">

    <%= link_to 'Payroll Application', root_path, class:"navbar-brand"%>
   
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button> 

      <ul class="navbar-nav">               
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">       
            <%if signed_in?%>
              <li class="nav-item">
                <%= link_to 'signout', destroy_user_session_path, class:"nav-link"%>        
              </li>
            <%else%>
              <li class="nav-item">
                <%= link_to 'signin', new_user_session_path, class:"nav-link"%>        
              </li>       
            <%end%>    
        </ul>                
      </ul> 

  </div>
  
</nav>

app/views/home/index.html.erb
<%if signed_in?%>
  <div>
    <h5>Welcome  <%=current_user.first_name%>!</h5>
  </div>
<%end%>
<div class="col-6" style="margin : 0 auto;">
  <h3>Payroll Management Software</h3><br/>
  <div style="color: magenta">
    <h2>Make The Biggest Cost</h2><br/>
    <h2>&nbsp&nbsp&nbsp&nbsp&nbspThe Smallest Of Worries</h2>
  </div><br/>
  <div>
    <p>Simplify enterprise payroll complexities with a powerfully secure, accurate,
      automated and 100% compliant payroll system, without breaking a sweat!</p>
  </div>
</div>