config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: "home#index"
  #devise_for :users
  
  devise_for :users, controllers: { sessions: 'users/sessions', 
    registrations: 'users/registrations',
  }

  namespace :users do
    resources :admins
    resources :employees 
    
  end

  resources :leaves
  resources :attendances
  resources :salaries
  resources :tax_deductions
  resources :payslips
 
  #get '/my_leaves/:current_user.id', to: 'leaves#my_leaves'
end

app/models/salary.rb
# frozen_string_literal: true

class Salary < ApplicationRecord
  belongs_to :employee

  validates :total_salary, :employee_id, :date, presence: true
end

app/controllers/salaries_controller.rb
# frozen_string_literal: true

class SalariesController < ApplicationController
  before_action :fetch_salary, only: %i[show edit update destroy]

  def index
    if authorised_admin?
      @salaries = Salary.all
    elsif authorised_employee?
      @salaries = Salary.where(employee_id: current_user.id)
    else
      flash[:alert] = I18n.t('unauthorised')
      redirect_to root_path
    end
  end

  def show
    @salary = Salary.find(params[:id])
    if authorised_admin? || authorised_employee?
      @salary = Salary.find(params[:id])
    else
      flash[:alert] = I18n.t('unauthorised')
      redirect_to root_path
    end
  end

  def new
    if authorised_admin?
      @salary = Salary.new
    else
      flash[:alert] = I18n.t('unauthorised')
      redirect_to root_path
    end
  end

  def create
    @salary = Salary.new(salary_params)
    updated_date = @salary.date.beginning_of_month
    @existing_salary = Salary.where(employee_id: @salary.employee_id, date: updated_date).first
    if authorised_admin?
      if !@existing_salary.present?
        @salary.date = updated_date
        flash[:notice] = if @salary.save
                           I18n.t('successful')
                         else
                           'Invalid details'
                         end
      else
        flash[:alert] = 'Already exits'
      end
    else
      flash[:alert] = I18n.t('unauthorised')
    end
    redirect_to salaries_path
  end

  def edit; end

  def update
    if authorised_admin? && @salary.update(salary_params)
      flash[:notice] = I18n.t('successful')
      redirect_to salaries_path
    else
      flash[:alert] = I18n.t('unauthorised')
      redirect_to root_path
    end
  end

  def destroy
    if @salary.destroy && authorised_admin?
      flash[:notice] = I18n.t('destroyed')
    else
      flash[:alert] = I18n.t('unauthorised')
    end
    redirect_to salaries_path
  end

  protected

  def fetch_salary
    @salary = Salary.find(params[:id])
  end

  def salary_params
    params.require(:salary).permit(:date, :total_salary, :employee_id)
  end
end

app/helpers/salaries_helper.rb
module SalariesHelper

end

app/views/salaries/_form.html.erb
<%= form_for(@salary, url: salaries_path) do |form| %>

  <table>

    <tr>

      <div>
        <td><%= form.label :date, "Date: " %></td>
        <td><%= form.date_field :date, discard_day: true %></td> 
      </div>

    </tr> 

    <tr>

      <div>
        <td><%= form.label :total_salary, 'Total salary: '%></td>
        <td><%= form.number_field :total_salary, min: "0" %></td>
      </div>

    </tr>
    
    <tr>

      <div>
        <td><%= form.label :employee_id, 'Employee name: '%></td>
        <td> <%= form.collection_select :employee_id, Employee.all, :id, :first_name, prompt: true %></td>
      </div>

    </tr>    
    
  </table></br>

  <div class="col-3", style="margin: 0 auto;">
    <%= form.submit class: "btn btn-warning"%>
  </div>
<% end %>

app/views/salaries/edit.html.erb
<div class="col-6" style="margin : 0 auto;">

  <div class="col-8" style="margin : 0 auto;">

    <h2>Edit Salary</h2></br>

  </div>
 
  <%= form_for(@salary, url: salary_path) do |form| %>

    <table>

      <tr>

        <div>        
          <td><%= form.label :date, "Date: " %></td>
          <td><%= form.date_field :date, discard_day: true %></td> 
        </div>

      </tr> 

      <tr>

        <div>
          <td><%= form.label :total_salary, 'Total salary: '%></td>
          <td><%= form.number_field :total_salary, min: "0" %></td>
        </div>

      </tr>

    </table></br>

    <div class="col-3", style="margin: 0 auto;">

      <%= form.submit class: "btn btn-warning"%>

    </div>
    
  <% end %>

</div>

app/views/salaries/index.html.erb
<div class="col-8" style="margin : 0 auto; padding: 10px">
  <h1>Employee salary data</h1></br>
</div>

<table class="table table-striped">

  <thead class="thead-light">

    <tr>
      <th>ID</th>
      <th>Employee ID</th>
      <th>Date</th>
      <th>Total salary</th>      
    </tr>

  </thead>

  <tbody>

    <% @salaries.each do |salary| %>
      <tr>
        <td><%= link_to "#{salary.id}", salary_path(salary), class:'btn btn-outline-primary', style:'width:40px'%></td>
        <td><%= salary.employee_id %></td>
        <td><%= salary.date%></td> 
        <td><%= salary.total_salary%></td>        
      </tr>

   <% end %>

  </tbody>

</table>

<%if current_user.type == 'Admin'%>

  <div class="col-2" style="margin : 0 auto; padding: 10px">
    <%= link_to 'Add new', new_salary_path, class: "btn btn-success" %>
  </div>
  
<%end%>

app/views/salaries/new.html.erb
<div class="col-6" style="margin : 0 auto;">

  <div class="col-8" style="margin : 0 auto;">

    <h2>Add Salary</h2></br>

  </div>

  <%= render "form", salary: @salary %>
  
</div>

app/views/salaries/show.html.erb
<div class="col-8" style="margin : 0 auto;">

  <table class="table table-striped">

    <thead style="color: blue">    
      <th><%= @salary.employee.first_name%>'s  Salary Details</th>
    </thead>

    <tbody>

      <tr>
        <th scope="row">ID</th>
        <td><%= @salary.employee.id %></td>      
      </tr>

      <tr>
        <th scope="row">Employee's  Name</th>
        <td><%= @salary.employee.first_name%></td>
      </tr>

      <tr>
        <th scope="row">Month</th>
        <td ><%= Date::MONTHNAMES[@salary.date.month] %></td>     
      </tr>

      <tr>
        <th scope="row">Total salary</th>
        <td ><%= @salary.total_salary %></td>     
      </tr>

    </tbody>

  </table>

  </br></br>

  <div class="d-flex justify-content-center">

    <div class="col-2">
      <%= link_to "Edit", edit_salary_path(@salary), class: "btn btn-warning"%> 
    </div>

    <div class="col-3">
      <%= button_to "Destroy", salary_path(@salary), class: "btn btn-danger", data: {:confirm => 'Are you sure?'}, method: :delete %>
    </div>

  </div> 
</div>