config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: "home#index"
  #devise_for :users
  
  devise_for :users, controllers: { sessions: 'users/sessions', 
    registrations: 'users/registrations',
  }

  namespace :users do
    resources :admins
    resources :employees 
    
  end

  resources :leaves
  resources :attendances
  resources :salaries
  resources :tax_deductions
  resources :payslips
 
  #get '/my_leaves/:current_user.id', to: 'leaves#my_leaves'
end

app/models/tax_deduction.rb
# frozen_string_literal: true

class TaxDeduction < ApplicationRecord
  belongs_to :employee
end

app/controllers/tax_deductions_controller.rb
# frozen_string_literal: true

class TaxDeductionsController < ApplicationController
  before_action :fetch_deduction, only: %i[show edit update destroy]

  def index
    if authorised_admin?
      @tax_deductions = TaxDeduction.all
    elsif authorised_employee?
      @tax_deductions = TaxDeduction.where(employee_id: current_user.id)
    else
      flash[:alert] = I18n.t('unauthorised')
      redirect_to root_path
    end
  end

  def show
    @tax_deduction = TaxDeduction.find(params[:id])
    if authorised_admin? || authorised_employee?
      @tax_deduction = TaxDeduction.find(params[:id])
    else
      flash[:alert] = I18n.t('unauthorised')
      redirect_to root_path
    end
  end

  def new
    if !authorised_admin? && authorised_employee?
      @tax_deduction = TaxDeduction.new
    else
      flash[:alert] = I18n.t('unauthorised')
      redirect_to root_path
    end
  end

  def create
    @tax_deduction = TaxDeduction.new(tax_deduction_params)
    if authorised_employee? && @tax_deduction.save
      flash[:notice] = I18n.t('successful')
      redirect_to tax_deductions_path
    else
      flash[:alert] = I18n.t('unauthorised')
      redirect_to root_path
    end
  end

  def edit
    if authorised_employee?
      
    else
      flash[:alert] = I18n.t('unauthorised')
      redirect_to tax_deductions_path
    end
  end

  def update
    if authorised_employee? && @tax_deduction.update(tax_deduction_params)
      flash[:notice] = I18n.t('successful')
    else
      flash[:alert] = I18n.t('unauthorised')
    end
    redirect_to tax_deductions_path
  end

  def destroy
    if @tax_deduction.destroy && authorised_employee?
      flash[:notice] = I18n.t('destroyed')
    else
      flash[:alert] = I18n.t('unauthorised')
    end
    redirect_to tax_deductions_path
  end

  protected

  def fetch_deduction
    @tax_deduction = TaxDeduction.find(params[:id])
  end

  def tax_deduction_params
    params.require(:tax_deduction).permit(:tax_type, :ammount, :employee_id, :financial_year)
  end
end

app/helpers/tax_deductions_helper.rb
module TaxDeductionsHelper
end

app/views/tax_deductions/_form.html.erb
<%= form_for(@tax_deduction, url: tax_deductions_path) do |form| %>

  <table>

   <tr>

      <div>
        <td><%= form.label :financial_year, 'Financial Year: '%></td>
        <td><%= form.select :financial_year, 1990..Date.today.year, :class => 'year'  %></td>
      </div>

    </tr>
    
    <tr>

      <div>
        <td><%= form.label :tax_type, "Tax Type: " %></td>
        <td><%= form.select :tax_type, ['NPS', 'Non-NPS']%></td> 
      </div>

    </tr> 

    <tr>

      <div>
        <td><%= form.label :ammount, 'Ammount: '%></td>
        <td><%= form.number_field :ammount, min: "0" %></td>
      </div>

    </tr>
    
    <tr>

      <div>
        <td><%= form.label :employee_id,"Employee Id: " %></td>
        <td><%= form.number_field :employee_id, value: current_user.id %></td>
      </div>

    </tr> 
   
    
  </table></br>

  <div class="col-3", style="margin: 0 auto;">
    <%= form.submit class: "btn btn-warning"%>
  </div>
  
<% end %>

app/views/tax_deductions/edit.html.erb
<div class="col-6" style="margin : 0 auto;">

  <h1>Updating Tax Deductions </h1></br>

  <%= form_for(@tax_deduction, url: tax_deduction_path) do |form| %>
    <table>
      <% if current_user.type == 'Employee' %>
        <tr>
          <div>
            <td><%= form.label :financial_year, 'Financial Year: '%></td>
            <td><%= form.select :financial_year, 1990..Date.today.year, :class => 'year'  %></td>
          </div>
        </tr>
     
        <tr>
          <div>
            <td><%= form.label :tax_type, "Tax Type: " %></td>
            <td><%= form.select :tax_type, ['NPS', 'Non-NPS']%></td> 
          </div>
        </tr> 

        <tr>
          <div>
            <td><%= form.label :ammount, 'Ammount: '%></td>
            <td><%= form.number_field :ammount, min: "0" %></td>
          </div>
        </tr>
     
      <% end %>
    
    </table></br>

    <div class="col-3", style="margin: 0 auto;">
      <%= form.submit class: "btn btn-warning"%>
    </div>

  <% end %> 

</div>

app/views/tax_deductions/index.html.erb
<div class="col-8" style="margin : 0 auto; padding: 10px">
  <h2>Employees Tax deductions</h2></br>
</div>

<table class="table table-striped">

  <thead class="thead-light">

    <tr>
      <th>ID</th>
      <th>Employee Id</th>
      <th>Tax type</th>
      <th>Total Ammount</th>
      <th>Financial Year</th>
    </tr>

  </thead>

  <tbody>

    <% @tax_deductions.each do |tax_deduction| %>

      <tr>
        <td><%= link_to "#{tax_deduction.id}", tax_deduction_path(tax_deduction),class:'btn btn-outline-primary', style:'width:40px'%></td>
        <td><%= tax_deduction.employee_id%></td>
        <td><%= tax_deduction.tax_type%></td> 
        <td><%= tax_deduction.ammount%></td>
        <td><%= tax_deduction.financial_year%></td>        
      </tr>

   <% end %>

  </tbody>

</table>

<% if current_user.type == 'Employee' %>
  <div class="col-2" style="margin : 0 auto; padding: 10px">
    <%= link_to 'Add new', new_tax_deduction_path, class: "btn btn-success" %>
  </div>
<% end %>

app/views/tax_deductions/new.html.erb
<div class="col-6" style="margin : 0 auto;">

  <div class="col-8" style="margin : 0 auto;">
    <h2>Tax Deduction Entry</h2></br>
  </div>

  <%= render "form", tax_deduction: @tax_deduction %>
  
</div>

app/views/tax_deductions/show.html.erb
<div class="col-8" style="margin : 0 auto;"> 

  <table class="table table-striped">

    <thead style="color: blue">
      <th><%= @tax_deduction.employee.first_name %>'s  Deductions Details</th>
    </thead>

    <tbody>

      <tr>
        <th scope="row">ID</th>
        <td><%= @tax_deduction.employee.id %></td>      
      </tr>

      <tr>
        <th scope="row">Employee's  Name</th>
        <td><%= @tax_deduction.employee.first_name  %></td>
      </tr>
      
      <tr>
        <th scope="row">Financial Year</th>
        <td ><%= @tax_deduction.financial_year %></td>     
      </tr>

      <tr>
        <th scope="row">Tax Type</th>
        <td ><%= @tax_deduction.tax_type %></td>     
      </tr> 

       <tr>
        <th scope="row">Deduction ammount</th>
        <td ><%= @tax_deduction.ammount %></td>     
      </tr> 

    </tbody>

  </table> 
 
  </br></br>

  <% if current_user.type == 'Employee'%>

  <div class="d-flex justify-content-center">  
    <div class="col-2">
      <%= link_to "Edit", edit_tax_deduction_path(@tax_deduction), class: "btn btn-warning"%> 
    </div>

    <div class="col-3">
      <%= button_to "Destroy", tax_deduction_path(@tax_deduction), class: "btn btn-danger", data: {:confirm => 'Are you sure?'}, method: :delete %>
    </div>

  </div>

<%end%>