config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: "home#index"
  #devise_for :users
  
  devise_for :users, controllers: { sessions: 'users/sessions', 
    registrations: 'users/registrations',
  }

  namespace :users do
    resources :admins
    resources :employees 
    
  end

  resources :leaves
  resources :attendances
  resources :salaries
  resources :tax_deductions
  resources :payslips
 
  #get '/my_leaves/:current_user.id', to: 'leaves#my_leaves'
end

app/models/attendance.rb
# frozen_string_literal: true

class Attendance < ApplicationRecord
  validates :month, presence: true
  validates :employee_id, presence: true

  belongs_to :employee
end

app/controllers/attendances_controller.rb
# frozen_string_literal: true

class AttendancesController < ApplicationController
  before_action :fetch_attendance, only: %i[show edit update destroy]

  def index
    if authorised_admin?
      @attendances = Attendance.all.order(:month)
    elsif authorised_employee?
      @attendances = Attendance.where(employee_id: current_user.id)
    else
      flash[:alert] = I18n.t('unauthorised')
      redirect_to root_path
    end
  end

  def show
    if authorised_admin? || authorised_employee?
      @attendance = Attendance.find(params[:id])
    else
      flash[:alert] = I18n.t('unauthorised')
      redirect_to '/attendances'
    end
  end

  def new
    @attendance = Attendance.new
  end

  def create
    @attendance = Attendance.new(attendance_params)
    if !Attendance.find_by(month: @attendance.month, employee_id: @attendance.employee_id)
      if authorised_admin? && @attendance.save
        @attendance.update(working_days: find_working_days(@attendance.id),
                           unpaid_leaves: find_total_unpaid_leaves(@attendance.id))
        flash[:notice] = I18n.t('successful')
      else
        flash[:alert] = I18n.t('unauthorised')
      end
    else
      flash[:alert] = 'Already exits'
    end
    redirect_to '/attendances'
  end

  def edit; end

  def update
    if @attendance.update(attendance_params)
      flash[:notice] = I18n.t('successful')
    else
      flash[:alert] = I18n.t('unauthorised')
    end
    redirect_to '/attendances'
  end

  def destroy
    if @attendance.destroy && authorised_admin?
      flash[:notice] = I18n.t('destroyed')
    else
      flash[:alert] = I18n.t('unauthorised')
    end
    redirect_to '/attendances'
  end

  protected

  def fetch_attendance
    @attendance = Attendance.find(params[:id])
  end

  def find_total_unpaid_leaves(id)
    @attendance = Attendance.find(id)
    @attendance.working_days = find_working_days(@attendance.id)
    leaves = Leave.where('extract(month from from_date) = ?',
                         @attendance.month).where(leave_type: 'unpaid').where(employee_id: @attendance.employee_id)
    @total_leaves = 0
    leaves.each do |leave|
      @total_leaves = @total_leaves + (leave.to_date - leave.from_date).to_i + 1 - skip_weekends(leave)
    end
    @total_leaves
  end

  def skip_weekends(leave)
    date = leave.from_date
    @office_days = 0
    until date  <= leave.to_date
      @office_days += 1 unless date.on_weekend?
      date = date.next
    end
    @office_days
  end

  def find_working_days(id)
    @attendance = Attendance.find(id)
    @office_days = 0
    date = Date.new(Date.today.year, @attendance.month, 1)
    until date >= date.end_of_month
      @office_days += 1 unless date.on_weekend?
      date = date.next
    end
    @office_days
  end

  def attendance_params
    params.require(:attendance).permit(:month, :unpaid_leaves, :working_days, :employee_id)
  end
end

app/helpers/attendances_helper.rb
module AttendancesHelper 
end

app/views/attendances/_form.html.erb
<%= form_for(@attendance, url: attendances_path) do |form| %>
  <table>
    <tr>
      <div>
        <td><%= form.label :month, "Month: " %></td>
        <td><%= form.select :month, options_for_select((1..12).map {|m| [Date::MONTHNAMES[m], format('%02d', m)]}), :required => true, :include_blank => "Select Month" %>  </td>
       
      </div>
    </tr>
    
    <tr>
      <div>
        <td><%= form.label :employee_id, 'Employee name: '%></td>
        <td> <%= form.collection_select :employee_id, Employee.all, :id, :first_name, prompt: true %></td>
      </div>
    </tr>  
       
  </table></br></br>

  <div class="col-8", style="margin: 0 auto;">
    <%= form.submit class: "btn btn-warning"%>
  </div>
<% end %>

app/views/attendances/edit.html.erb
<div class="col-6" style="margin : 0 auto;">
  <h2>Updating Attendance </h2></br>

  <%= form_for(@attendance, url: attendance_path) do |form| %>
    <table>
      <% if current_user.type == 'Admin' %>

        <tr>
          <div>
            <td><%= form.label :month, "Month: " %></td>
            <td><%= form.select :month, options_for_select((1..12).map {|m| [Date::MONTHNAMES[m], format('%02d', m)]}), :required => true, :include_blank => "Select Month" %>  </td>
          </div>
        </tr>

        <tr>
          <div>
            <td><%= form.label :unpaid_leaves, "Unpaid leaves: " %></td>
            <td><%= form.number_field :unpaid_leaves, max: "30" %></td>
          </div>
        </tr> 
  
      <% end %>  

    </table></br>

    <div class="col-3", style="margin: 0 auto;">
      <%= form.submit class: "btn btn-warning"%>
    </div>
  <% end %>
</div>

app/views/attendances/index.html.erb
<div class="col-6" style="margin : 0 auto; padding: 10px">
  <h1>Attendance data</h1></br>
</div>

<table class="table table-striped">

  <thead class="thead-light">
    <tr>
      <th>ID</th>
      <th>Employee ID</th>
      <th>Month</th>
      <th>Working Days</th>     
    </tr>
  </thead>

  <tbody>

    <% @attendances.each do |attendance| %>

      <tr>
        <td><%= link_to "#{attendance.id}", attendance_path(attendance), class:'btn btn-outline-primary', style:'width:40px'%></td>
        <td><%= attendance.employee_id %></td>
        <td><%= attendance.month%></td> 
        <td><%= attendance.working_days%></td>      
      </tr>

    <% end %>

  </tbody>

</table>

<div class="col-2" style="margin : 0 auto; padding: 10px">
  <%= link_to 'Add new', new_attendance_path, class: "btn btn-success" %>
</div>

app/views/attendances/new.html.erb
<div class="col-8" style="margin : 0 auto;">
  <div class="col-11" style="margin : 0 auto;">
    <h1>Attendance Enrollment</h1></br>
  </div>
  <%= render "form", attendance: @attendance %>
</div>

app/views/attendances/show.html.erb
<div class="col-8" style="margin : 0 auto;">  
  <table class="table table-striped">

    <thead style="color: blue">
      <th><%= @attendance.employee.first_name %>'s  attendance Details</th>
    </thead>

    <tbody>

      <tr>
        <th scope="row"> Employee ID</th>
        <td><%= @attendance.employee.id %></td>      
      </tr>

      <tr>
        <th scope="row">Employee's  Name</th>
        <td><%= @attendance.employee.first_name  %></td>
      </tr>

      <tr>
        <th scope="row">Month</th>
        <td ><%= @attendance.month %></td>     
      </tr>

      <tr>
        <th scope="row">Working days </th>
        <td ><%= @attendance.working_days %></td>     
      </tr>

      <tr>
        <th scope="row">Unpaid leaves</th>
        <td ><%= @attendance.unpaid_leaves %></td>     
      </tr>

    </tbody>

  </table>

  </br></br>
  
  <div class="d-flex justify-content-center">  
    <%# <div class="col-2">
      <%= link_to "Edit", edit_attendance_path(@attendance), class: "btn btn-warning"%> 
    <%# </div> %> 
    <div class="col-3">
      <%= button_to "Destroy", attendance_path(@attendance), class: "btn btn-danger", data: {:confirm => 'Are you sure?'}, method: :delete %>
    </div>
  </div> 
</div> 